### ISSUE TITLE
Conflict with dynaconf.com

### ISSUE THREAD

**Issue by ahcoronurb** [mhsiddiqui/django-dynaconf#1]
Hi,

I am the creator and maintainer of dynaconf.com and we also have a django settings extension,
so users of dynaconf.com would do `from dynaconf import Dynaconf`

I really like the idea of your project, it is similar to django-preferences and I think we can maybe join some efforts to make our both projects to work good together without conflicts.

The problem is that if some installs dynaconf and django-dynaconf that user will have conflict on importing `from dynaconf...` and also
that might lead to some confusion about the intention of the 2 projects sharing the same name and python namespace module.

Are you open to talk about what we can do in order to make your project compatible with dynaconf.com? that would involve

- changing namespace to avoid conflict, something like `from django_dynaconf` or `from dynaconf_admin` 
- implement some features from dynaconf.com such as mergins and casting
- include your extension as a loaded to override dynaconf.com settings
- add your project as a "plugin" for dynaconf.com?

I understand if you are not interested, so feel free to just close the issue, just add a notice that if user already has dynaconf.com it can lead to conflicts.

Thanks.

**Comment by mhsiddiqui** [comment]
Thank you for pointing out the issue and I really appreciate that. I will work on it on priority to change the namespace. It will be done in a few days. I am also open to your other ideas and will look into those as well.

**Comment by mhsiddiqui** [comment]
The issue has been resolved.
